### ISSUE TITLE
How to make the font-color of the menu darker

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/oma_github_pages#32]
The font color of the menu seems lighter than the font color of the body.

<img width="1291" alt="image" src="https://user-images.githubusercontent.com/3258579/160201519-55b82329-7831-4861-8d7a-9f9bd613eb8a.png">

**Comment by rubystream** [comment]
In in branch [style](https://github.com/OpenMobileAlliance/oma_github_pages/tree/style) in the commit 0f3fb0b the CSS rule for manipulating the main navigation menu items is introduced.

```css
/* changing the font of the main navigation menu */
.navbar-light .navbar-nav .nav-link {
  color: #000;
  font-weight: 300;
}
```

This can be adjusted to desired needs.
